const path = require("path")
const fs = require("fs/promises")

// It's impossible to change the default ui directory generated by shadcn-ui cli
// So, we manually move the files from components/ui to components
// And add export statements in the index.tsx
const main = async () => {
  try {
    const uiDir = path.resolve(__dirname, "../src/components/ui")
    const componentDir = path.resolve(__dirname, "../src/components")
    const entryFile = path.resolve(__dirname, "../src/index.tsx")

    const components = await fs.readdir(uiDir)
    for (const component of components) {
      await fs.rename(
        path.resolve(uiDir, component),
        path.resolve(componentDir, component)
      )
      // Remove the empty ui directory
      await fs.rm(uiDir, { recursive: true, force: true })

      const name = component.split(".")[0]
      const statements = await fs.readFile(path.resolve(entryFile), "utf-8")
      console.log(statements)
      // Make sure we don't add duplicate export statements
      if (statements.includes(`export * from "./components/${name}"`)) {
        continue
      }
      await fs.appendFile(entryFile, `export * from "./components/${name}"\n`)
    }
  } catch (error) {
    console.error("Something failed:", error)
  }
}

main()
