export const FLOW_NODE_MARGIN_HORIZONTAL = 15
export const FLOW_NODE_MARGIN_VERTICAL = 10
export const FLOW_NODE_PADDING_VERTICAL = 10
export const FLOW_NODE_PADDING_HORIZONTAL = 20
export const FLOWCHART_PADDING_HORIZONTAL = 20
export const FLOWCHART_PADDING_VERTICAL = 20
export const FLOW_NODE_BORDER_RADIUS = 5
export const FLOW_CHOICE_PADDING_HORIZONTAL = 20
