export const FLOW_NODE_MARGIN_LEFT = 20
export const FLOW_NODE_MARGIN_TOP = 20
export const FLOW_NODE_PADDING_TOP = 10
export const FLOW_NODE_PADDING_LEFT = 20
export const FLOWCHART_PADDING_LEFT = 20
export const FLOWCHART_PADDING_TOP = 20
export const FLOW_NODE_BORDER_RADIUS = 5
