// GRAPH
export const GRAPH_TEXT_FONT_SIZE = 16
export const GRAPH_TEXT_LIEN_HEIGHT = GRAPH_TEXT_FONT_SIZE * 1.5
export const GRAPH_NODE_PADDING_VERTICAL = 4
export const GRAPH_NODE_PADDING_HORIZONTAL = 10
export const GRAPH_NODE_BORDER_RADIUS = 5
export const GRAPH_NODE_MARGIN_VERTICAL = 15
export const GRAPH_NODE_MARGIN_HORIZONTAL = 25
export const GRAPH_GROUP_NODE_PADDING_VERTICAL = 15
export const GRAPH_CHOICE_PADDING_HORIZONTAL = 25
export const GRAPH_ROOT_RADIUS = 10
export const GRAPH_NODE_MIN_WIDTH = 20
export const GRAPH_NODE_MIN_HEIGHT = 26
export const GRAPH_QUANTIFIER_ICON_WIDTH = 28
export const GRAPH_QUANTIFIER_ICON_HEIGHT = 16
export const GRAPH_QUANTIFIER_TEXT_FONTSIZE = 12
export const GRAPH_QUANTIFIER_ICON_MARGIN_VERTICAL = 4
export const GRAPH_NAME_TEXT_FONTSIZE = 12
export const GRAPH_NAME_HEIGHT = 10

export const GRAPH_PADDING_VERTICAL = 50
export const GRAPH_PADDING_HORIZONTAL = 50
export const GRAPH_MINIMUM_PADDING_VERTICAL = 5
export const GRAPH_MINIMUM_PADDING_HORIZONTAL = 5
