export const CHART_PADDING_HORIZONTAL = 50
export const CHART_PADDING_VERTICAL = 50

export const NODE_PADDING_VERTICAL = 8
export const NODE_PADDING_HORIZONTAL = 10

export const NODE_MARGIN_VERTICAL = 15
export const NODE_MARGIN_HORIZONTAL = 25

export const BRANCH_PADDING_HORIZONTAL = 10

export const NODE_BORDER_RADIUS = 5
export const ROOT_RADIUS = 5
export const QUANTIFIER_HEIGHT = 20
export const NAME_HEIGHT = 10
